"""Initial migration - create all tables

Revision ID: 001
Revises:
Create Date: 2026-02-01 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create employees table
    op.create_table(
        'employees',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('telegram_id', sa.BigInteger(), nullable=True),
        sa.Column('telegram_username', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('telegram_id')
    )
    
    # Create receipts table
    op.create_table(
        'receipts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('receipt_number', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')),
        sa.Column('current_deadline', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('receipt_number')
    )
    
    # Create operation_types table
    op.create_table(
        'operation_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    
    # Create operations table
    op.create_table(
        'operations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('receipt_id', sa.Integer(), nullable=False),
        sa.Column('operation_type_id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.id']),
        sa.ForeignKeyConstraint(['operation_type_id'], ['operation_types.id']),
        sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id']),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create polishing_details table
    op.create_table(
        'polishing_details',
        sa.Column('receipt_id', sa.Integer(), nullable=False),
        sa.Column('polisher_id', sa.Integer(), nullable=False),
        sa.Column('metal_type', sa.String(), nullable=False),
        sa.Column('bracelet', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('difficult', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('sent_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')),
        sa.Column('returned_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['polisher_id'], ['employees.id']),
        sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id']),
        sa.PrimaryKeyConstraint('receipt_id')
    )
    
    # Create returns table
    op.create_table(
        'returns',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('receipt_id', sa.Integer(), nullable=False),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')),
        sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id']),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create return_reasons table
    op.create_table(
        'return_reasons',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('affects', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    
    # Create return_reason_links table
    op.create_table(
        'return_reason_links',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('return_id', sa.Integer(), nullable=False),
        sa.Column('reason_id', sa.Integer(), nullable=False),
        sa.Column('guilty_employee_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['guilty_employee_id'], ['employees.id']),
        sa.ForeignKeyConstraint(['reason_id'], ['return_reasons.id']),
        sa.ForeignKeyConstraint(['return_id'], ['returns.id']),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create history_events table
    op.create_table(
        'history_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('receipt_id', sa.Integer(), nullable=False),
        sa.Column('event_type', sa.String(), nullable=False),
        sa.Column('payload', sa.JSON(), nullable=True),
        sa.Column('telegram_id', sa.BigInteger(), nullable=True),
        sa.Column('telegram_username', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')),
        sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id']),
        sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_events')
    op.drop_table('return_reason_links')
    op.drop_table('return_reasons')
    op.drop_table('returns')
    op.drop_table('polishing_details')
    op.drop_table('operations')
    op.drop_table('operation_types')
    op.drop_table('receipts')
    op.drop_table('employees')
    # ### end Alembic commands ###
